### ISSUE TITLE
Version 0.8 of the paper

### ISSUE THREAD

**Issue by gully** [gully/blase#45]
Yay, I sent version "0.7" of the paper to @astrocaroline, while that review is underway, there are a few placeholders to fill-in:

- [x] IGRINS Sonora-Bobcat demo figure and text (Section 5.5) and Issue #41 
- [x] Injection recovery test figure (Section 5.6) and Issue #42 
- [x] Figure 4-- Replace with a telluric demo, may require redoing the whole figure sequence to illustrate a region with telluric lines (see the [step-by-step tutorial](https://blase.readthedocs.io/en/latest/tutorials/index.html)) #37 
- [x] Write conclusions
- [x] Re-order the presentation of the Extensions section? (Section 7) #43 ...also emphasize modularity for separable physics
- [x] Put in a blurb about how to calibrate Teff and logg (Section 7.x) #44

**Comment by gully** [comment]
Woohoo, we have a stub for conclusions, so we'll make that "nice" but otherwise paper is looking solid.  Giving it an end-to-end read through right now.
